/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jGnssConverion;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bhoj Raj
 */
public class GnssConversion extends javax.swing.JFrame {
    
    SimpleDateFormat df= new SimpleDateFormat("YYYY/MM/DD");
    
    Calendar cal= new GregorianCalendar(1980,00,01);
     
     
     private int ddoy;
     private int wgps;
     private int seconds;
     private int remainder=0;
     private int days=0;
     private int hours=0;
     private int minutes=0;
     private int residue=0;
     private String Weekday;
     // WGS84 ellipsoid constants
    private final double a = 6378.137; // radius in kilometers
    private final double e = 8.1819190842622e-2;  // eccentricity
    private final double asq = Math.pow(a,2);
    private final double esq = Math.pow(e,2);
    // Formatting
    DecimalFormat formatter = new DecimalFormat("#0.0000");
  
      
    public GnssConversion() {
        
        initComponents();
    }
    
     void convertDoytoYear(String inputDOY){
         
                
                ddoy= Integer.parseInt(inputDOY);
               // System.out.println(Integer.parseInt(""));
                wgps= Integer.parseInt(txtGPSWeek.getText());
                Integer rem;// To find out the reminder of DOY divided by 7
                rem= ddoy % 7;
                
               //System.out.println(df.format(cal.getTime()));
                String dt = "1980-01-01";  // Start date
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Calendar c = Calendar.getInstance();
        try {
            c.setTime(sdf.parse(dt));
        } catch (ParseException ex) {
            Logger.getLogger(GnssConversion.class.getName()).log(Level.SEVERE, null, ex);
        }
               //c.add(Calendar.DATE, ddoy);  // number of days to add
                c.add(Calendar.WEEK_OF_YEAR, wgps);// number of weeks to add
                c.add(Calendar.DATE,rem-1); // add the remainder to get the exact date
                dt = sdf.format(c.getTime());  // dt is now the new date
                txtDateDOY.setText(dt);
                
        
        
             
              
    }
void convertToDayTime(String InputSeconds){
    seconds= Integer.parseInt(InputSeconds);
    int days= seconds/(60*60*24);
    residue= seconds % (60*60*24);
    hours=residue/(60*60);
    residue= residue%(60*60);
    minutes= residue/60;
    seconds= residue%60;
    
    switch(days){
            case 0:
            Weekday="Sunday";
            break;
            case 1:
            Weekday="Monday";
            break;
            case 2:
            Weekday="Tuesday";
            break;
            case 3:
            Weekday="Wednesday";
            break;
            case 4:
            Weekday="Thursday";
            break;
            case 5:
            Weekday="Friday";
            break;
            case 6:
            Weekday="Saturday";
            break;
        }
    txtDay.setText(Weekday);
    txtTime.setText(hours+":"+minutes + ":"+seconds);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBasic = new javax.swing.JPanel();
        pnlToDate = new javax.swing.JPanel();
        txtDOY = new javax.swing.JTextField();
        txtGPSWeek = new javax.swing.JTextField();
        btnDOY = new javax.swing.JButton();
        btnGPSSec = new javax.swing.JButton();
        txtDateDOY = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        btnDOYClr = new javax.swing.JButton();
        lblDOY = new javax.swing.JLabel();
        lblGPSWeek = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        pnlECEFllh = new javax.swing.JPanel();
        lblECEF = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        lblZ = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();
        txtZ = new javax.swing.JTextField();
        lblLLH = new javax.swing.JLabel();
        lblLatN = new javax.swing.JLabel();
        txtLatN = new javax.swing.JTextField();
        lblLonE = new javax.swing.JLabel();
        txtLonE = new javax.swing.JTextField();
        lblHeighte = new javax.swing.JLabel();
        txtHeighte = new javax.swing.JTextField();
        btnECEFtoLLH = new javax.swing.JButton();
        btnLLH2ECEF = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        pnlENUAzEl = new javax.swing.JPanel();
        lblSatellite = new javax.swing.JLabel();
        lblSatx = new javax.swing.JLabel();
        txtSatx = new javax.swing.JTextField();
        lblSaty = new javax.swing.JLabel();
        txtSaty = new javax.swing.JTextField();
        lblSatz = new javax.swing.JLabel();
        txtSatz = new javax.swing.JTextField();
        lblGivenPosition = new javax.swing.JLabel();
        lblRx = new javax.swing.JLabel();
        txtRx = new javax.swing.JTextField();
        lblRy = new javax.swing.JLabel();
        txtRy = new javax.swing.JTextField();
        lblRz = new javax.swing.JLabel();
        txtRz = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        btnClearx = new javax.swing.JButton();
        lblGivenPosition1 = new javax.swing.JLabel();
        lblEast = new javax.swing.JLabel();
        txtEast = new javax.swing.JTextField();
        lblRy1 = new javax.swing.JLabel();
        txtNorth = new javax.swing.JTextField();
        lblUp = new javax.swing.JLabel();
        txtUp = new javax.swing.JTextField();
        lblAzEl = new javax.swing.JLabel();
        lblAz = new javax.swing.JLabel();
        txtAz = new javax.swing.JTextField();
        lblRy2 = new javax.swing.JLabel();
        txtEl = new javax.swing.JTextField();
        lblSatellite1 = new javax.swing.JLabel();
        lblSatx1 = new javax.swing.JLabel();
        txtSatB = new javax.swing.JTextField();
        lblSaty1 = new javax.swing.JLabel();
        txtSatL = new javax.swing.JTextField();
        lblSatz1 = new javax.swing.JLabel();
        txtSatH = new javax.swing.JTextField();
        lblGivenPosition2 = new javax.swing.JLabel();
        lblRx1 = new javax.swing.JLabel();
        txtRB = new javax.swing.JTextField();
        lblRy3 = new javax.swing.JLabel();
        txtRL = new javax.swing.JTextField();
        lblRz1 = new javax.swing.JLabel();
        txtRH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Space Calculator");

        txtDOY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOYActionPerformed(evt);
            }
        });

        btnDOY.setText("Convert");
        btnDOY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOYActionPerformed(evt);
            }
        });

        btnGPSSec.setText("Convert");
        btnGPSSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGPSSecActionPerformed(evt);
            }
        });

        txtDateDOY.setEditable(false);
        txtDateDOY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateDOYActionPerformed(evt);
            }
        });

        btnDOYClr.setText("Clear");
        btnDOYClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOYClrActionPerformed(evt);
            }
        });

        lblDOY.setText("DOY");

        lblGPSWeek.setText("GPS Week");

        jLabel1.setText("Sec");

        txtDay.setEditable(false);

        txtTime.setEditable(false);

        javax.swing.GroupLayout pnlToDateLayout = new javax.swing.GroupLayout(pnlToDate);
        pnlToDate.setLayout(pnlToDateLayout);
        pnlToDateLayout.setHorizontalGroup(
            pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDOY, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOY, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlToDateLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblGPSWeek))
                    .addGroup(pnlToDateLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGPSSec)))
                .addGap(38, 38, 38)
                .addGroup(pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlToDateLayout.createSequentialGroup()
                        .addComponent(txtGPSWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnDOY))
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDateDOY, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(txtTime))
                .addGap(18, 18, 18)
                .addComponent(btnDOYClr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlToDateLayout.setVerticalGroup(
            pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDOY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGPSWeek)
                    .addComponent(txtGPSWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDOY)
                    .addComponent(txtDateDOY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDOYClr))
                .addGap(18, 18, 18)
                .addGroup(pnlToDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGPSSec)
                    .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(txtDay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblECEF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblECEF.setText("ECEF Coordinate");

        lblX.setText("X-Coordinate");

        lblY.setText("Y- Coordinate");

        lblZ.setText("Z- Coordinate");

        lblLLH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLLH.setText("LLH Coordinate");

        lblLatN.setText("Latitude -N");

        lblLonE.setText("Longitute -E");

        lblHeighte.setText("Height- ellepsoid");

        btnECEFtoLLH.setLabel("Convert ECEF 2 LLH");
        btnECEFtoLLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnECEFtoLLHActionPerformed(evt);
            }
        });

        btnLLH2ECEF.setText("Convert LLH 2 ECEF");
        btnLLH2ECEF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLLH2ECEFActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblSatellite.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSatellite.setText("Satellite Position (ECEF)");

        lblSatx.setText("X:");

        txtSatx.setEditable(false);

        lblSaty.setText("Y:");

        txtSaty.setEditable(false);
        txtSaty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatyActionPerformed(evt);
            }
        });

        lblSatz.setText("Z:");

        txtSatz.setEditable(false);

        lblGivenPosition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGivenPosition.setText("Receiver Position (ECEF)");

        lblRx.setText("X0:");

        txtRx.setEditable(false);

        lblRy.setText("Y0:");

        txtRy.setEditable(false);

        lblRz.setText("Z0:");

        txtRz.setEditable(false);

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnClearx.setText("Clear");
        btnClearx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearxActionPerformed(evt);
            }
        });

        lblGivenPosition1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGivenPosition1.setText("ENU Position (E,N,U)");

        lblEast.setText("East (Km)");

        txtEast.setEditable(false);

        lblRy1.setText("North (Km)");

        txtNorth.setEditable(false);

        lblUp.setText("Up (Km)");

        txtUp.setEditable(false);

        lblAzEl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAzEl.setText("Value of Az and El at Rx (x0,y0,z0)");

        lblAz.setText("Az(Deg)");

        txtAz.setEditable(false);

        lblRy2.setText("E(Deg)");

        txtEl.setEditable(false);

        lblSatellite1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSatellite1.setText("Satellite Position (B,L,H)");

        lblSatx1.setText("Lat(deg)");

        txtSatB.setText("0");

        lblSaty1.setText("Lon(deg)");

        txtSatL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatLActionPerformed(evt);
            }
        });

        lblSatz1.setText("Height(km)");

        txtSatH.setText("42166");

        lblGivenPosition2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGivenPosition2.setText("Receiver Position (B,L,H)");

        lblRx1.setText("Lat(deg)");

        lblRy3.setText("Lon(deg)");

        lblRz1.setText("Height(km)");

        txtRH.setText("0");

        javax.swing.GroupLayout pnlENUAzElLayout = new javax.swing.GroupLayout(pnlENUAzEl);
        pnlENUAzEl.setLayout(pnlENUAzElLayout);
        pnlENUAzElLayout.setHorizontalGroup(
            pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlENUAzElLayout.createSequentialGroup()
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addComponent(lblGivenPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEast, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEast, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addComponent(lblAzEl, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearx, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRx, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRy1)
                            .addComponent(lblAz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAz, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaty, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSatL, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNorth, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))
                    .addGroup(pnlENUAzElLayout.createSequentialGroup()
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGivenPosition)
                            .addComponent(lblSatellite)
                            .addComponent(lblSatellite1)
                            .addComponent(lblGivenPosition2))
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblRx, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlENUAzElLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSatx1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSatx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRx1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRB)
                            .addComponent(txtSatx, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(txtSatB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addComponent(lblRy3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRz1))
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addComponent(lblSaty, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRy2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSatz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblRy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(txtRy, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRz, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addComponent(lblSaty1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSatz1)
                                .addGap(6, 6, 6)))
                        .addGap(18, 18, 18)))
                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlENUAzElLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(btnCalculate))
                        .addComponent(txtRH, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSatz, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRz, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSatH, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pnlENUAzElLayout.setVerticalGroup(
            pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlENUAzElLayout.createSequentialGroup()
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSatellite1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSatx1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSatB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSaty1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSatL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSatellite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSatx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSatx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSaty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSaty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtRH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRz1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblGivenPosition2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblRx1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRy3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlENUAzElLayout.createSequentialGroup()
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSatH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSatz1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSatz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSatz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlENUAzElLayout.createSequentialGroup()
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtRz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblGivenPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblRx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlENUAzElLayout.createSequentialGroup()
                        .addComponent(txtRy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGivenPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRy1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNorth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlENUAzElLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlENUAzElLayout.createSequentialGroup()
                        .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(pnlENUAzElLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAz, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRy2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlENUAzElLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAzEl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );

        javax.swing.GroupLayout pnlECEFllhLayout = new javax.swing.GroupLayout(pnlECEFllh);
        pnlECEFllh.setLayout(pnlECEFllhLayout);
        pnlECEFllhLayout.setHorizontalGroup(
            pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlECEFllhLayout.createSequentialGroup()
                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlECEFllhLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlECEFllhLayout.createSequentialGroup()
                                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblECEF)
                                    .addComponent(lblLLH, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblX)
                                    .addComponent(lblLatN)))
                            .addGroup(pnlECEFllhLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnECEFtoLLH)))
                        .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlECEFllhLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnLLH2ECEF)
                                .addGap(83, 83, 83)
                                .addComponent(btnClear))
                            .addGroup(pnlECEFllhLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLatN, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(txtX))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlECEFllhLayout.createSequentialGroup()
                                        .addComponent(lblY)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtY))
                                    .addGroup(pnlECEFllhLayout.createSequentialGroup()
                                        .addComponent(lblLonE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLonE, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlECEFllhLayout.createSequentialGroup()
                                        .addComponent(lblZ)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtZ, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlECEFllhLayout.createSequentialGroup()
                                        .addComponent(lblHeighte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHeighte, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnlECEFllhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlENUAzEl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlECEFllhLayout.setVerticalGroup(
            pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlECEFllhLayout.createSequentialGroup()
                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblECEF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtZ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblZ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLLH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLatN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLatN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLonE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLonE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeighte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeighte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlECEFllhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnECEFtoLLH)
                        .addComponent(btnLLH2ECEF))
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(pnlENUAzEl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBasicLayout = new javax.swing.GroupLayout(pnlBasic);
        pnlBasic.setLayout(pnlBasicLayout);
        pnlBasicLayout.setHorizontalGroup(
            pnlBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasicLayout.createSequentialGroup()
                .addGroup(pnlBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBasicLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pnlToDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBasicLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlECEFllh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlBasicLayout.setVerticalGroup(
            pnlBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlToDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlECEFllh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDOYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOYActionPerformed
        // TODO add your handling code here:
        String doy;
        //String gweek;
        doy= txtDOY.getText();
        //gweek= txtGPSWeek.getText();
        convertDoytoYear(doy);
    }//GEN-LAST:event_btnDOYActionPerformed

    private void btnDOYClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOYClrActionPerformed
        // TODO add your handling code here:
        txtDateDOY.setText("");
        txtDOY.setText("");
        txtGPSWeek.setText("");
        txtSecond.setText("");
        txtDay.setText("");
        txtTime.setText("");
        cal= new GregorianCalendar(1980,01,01);
        
    }//GEN-LAST:event_btnDOYClrActionPerformed

    private void txtDOYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOYActionPerformed

    private void txtDateDOYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateDOYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateDOYActionPerformed

    private void btnGPSSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGPSSecActionPerformed
        // TODO add your handling code here:
        String seconds;
        seconds=txtSecond.getText();
        convertToDayTime(seconds);
    }//GEN-LAST:event_btnGPSSecActionPerformed

    private void btnECEFtoLLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnECEFtoLLHActionPerformed
        // TODO add your handling code here:
        String x = txtX.getText();
        String y= txtY.getText();
        String z= txtZ.getText();
        ecef2llh(x,y,z);
        
        
    }//GEN-LAST:event_btnECEFtoLLHActionPerformed
private void ecef2llh(String x, String y, String z){
  double inputx = Double.parseDouble(x);
  double inputy= Double.parseDouble(y);
  double inputz= Double.parseDouble(z);
  
  double b = Math.sqrt( asq * (1-esq) );
  double bsq = Math.pow(b,2);
  double ep = Math.sqrt( (asq - bsq)/bsq);
  double p = Math.sqrt( Math.pow(inputx,2) + Math.pow(inputy,2) );
  double th = Math.atan2(a*inputz, b*p);
 
  double lon = Math.atan2(inputy,inputx);
  double lat = Math.atan2( (inputz + Math.pow(ep,2)*b*Math.pow(Math.sin(th),3) ), (p - esq*a*Math.pow(Math.cos(th),3)) );
  double N = a/( Math.sqrt(1-esq*Math.pow(Math.sin(lat),2)) );
  double alt = p / Math.cos(lat) - N;
 
  // mod lat to 0-2pi
  lon = lon % (2*Math.PI);
 
  // correction for altitude near poles left out.
 
  //Display part
  txtLonE.setText(String.valueOf(formatter.format(lon)));
  txtLatN.setText(String.valueOf(formatter.format(lat)));
  txtHeighte.setText(String.valueOf(formatter.format(alt)));
  
}
private double [] convertLLHtoECEF(double b, double l, double h)
{
    double N = a / (Math.sqrt(1 - esq * Math.pow(Math.sin(Math.toRadians(b)),2)) );
    double dispx = (N+h) * Math.cos(Math.toRadians(b)) * Math.cos(Math.toRadians(l));
    //System.out.println(dispx);
    double dispy = (N+h) * Math.cos(Math.toRadians(b)) * Math.sin(Math.toRadians(l));
    double dispz = ((1-esq) * N + h) * Math.sin(Math.toRadians(b));
    double ecefxyz[]={dispx,dispy,dispz};
    return ecefxyz;
}
//Function to convert LLH to ECEF from textbox input. This function needs refactoring with return parameters.
private void llh2ecef(String xa, String yb, String zc){
  
  double inputlat = Double.parseDouble(xa);
 
  double inputlong= Double.parseDouble(yb);
  double inputalt= Double.parseDouble(zc);
   
  double N = a / (Math.sqrt(1 - esq * Math.pow(Math.sin(Math.toRadians(inputlat)),2)) );
 
  double dispx = (N+inputalt) * Math.cos(Math.toRadians(inputlat)) * Math.cos(Math.toRadians(inputlong));
  //System.out.println(dispx);
   
  double dispy = (N+inputalt) * Math.cos(Math.toRadians(inputlat)) * Math.sin(Math.toRadians(inputlong));
  
  double dispz = ((1-esq) * N + inputalt) * Math.sin(Math.toRadians(inputlat));
   
  //Formatting Output
  
  
  //Display part
//  System.out.println(dispx);
//  System.out.println(dispy);
//  System.out.println(dispz);
  
  txtX.setText(String.valueOf(formatter.format(dispx)));
  txtY.setText(String.valueOf(formatter.format(dispy)));
  txtZ.setText(String.valueOf(formatter.format(dispz)));
  
}
    private void btnLLH2ECEFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLLH2ECEFActionPerformed
        // TODO add your handling code here:
        String x11 = txtLatN.getText();
        String y11= txtLonE.getText();
        String z11= txtHeighte.getText();
        llh2ecef(x11,y11,z11);
    }//GEN-LAST:event_btnLLH2ECEFActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtX.setText("");
        txtY.setText("");
        txtZ.setText("");
        txtLatN.setText("");
        txtLonE.setText("");
        txtHeighte.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        // Read the BLH(lat, long, height) parameters of Satellite position 
        double satB= Double.parseDouble(txtSatB.getText());// latitude of Satellite(Its zero for geostationary satellites)
        double satL= Double.parseDouble(txtSatL.getText());// Longitude of Satellite
        double satH= Double.parseDouble(txtSatH.getText());// Height of Satellite ( Its generally 42166 km)
        double satCoordinate[]= convertLLHtoECEF(satB,satL,satH);// Function call for conversion of LLH to ECEF
        System.out.println(satCoordinate[0]);
        // Display the satellite coordinate in terms of ECEF format.
        txtSatx.setText(String.valueOf(formatter.format(satCoordinate[0])));
        txtSaty.setText(String.valueOf(formatter.format(satCoordinate[1])));
        txtSatz.setText(String.valueOf(formatter.format(satCoordinate[2])));
        
        // Read the BLH (Lat, Long Height) parameters of Receiver position
        
        double rB= Double.parseDouble(txtRB.getText());// Latitude of Receiver Station
        double rL= Double.parseDouble(txtRL.getText());// Longitude of Satellite
        double rH= Double.parseDouble(txtRH.getText());// Height of Receiver Station ( Normally zero)
        double receiverCoordinate[]= convertLLHtoECEF(rB,rL,rH);// Function call for conversion of LLH to ECEF
       
        
        // Display the receiver coordinate in terms of ECEF format.
        txtRx.setText(String.valueOf(formatter.format(receiverCoordinate[0])));
        //System.out.println(receiverCoordinate[0]);
        txtRy.setText(String.valueOf(formatter.format(receiverCoordinate[1])));
        txtRz.setText(String.valueOf(formatter.format(receiverCoordinate[2])));
        
        // Calculate the difference of satellite coordinate and receiver coorddinates in ECEF format
        
        
//        double satx = Double.parseDouble(txtSatx.getText());
//        double saty= Double.parseDouble(txtSaty.getText());
//        double satz= Double.parseDouble(txtSatz.getText());
//        double rx= Double.parseDouble(txtRx.getText());
//        double ry= Double.parseDouble(txtRy.getText());
//        double rz= Double.parseDouble(txtRz.getText());
//        double lambda= Double.parseDouble(txtLambda.getText());
//        double phi= Double.parseDouble(txtPhi.getText());
        // Find out the difference between the two position i.e, satellite position and the other position R.
        double dx= satCoordinate[0]-receiverCoordinate[0];
        double dy= satCoordinate[1]-receiverCoordinate[1];
        double dz= satCoordinate[2]-receiverCoordinate[2];
        
        // Set lambda= longitude of Receiver and phi = latitude of receiver
        double phi= Double.parseDouble(txtRB.getText());//Latitude of receiver
        double lambda= Double.parseDouble(txtRL.getText());// Longitude of Receiver
        
        
        // Collect necessary value for Rz(-90),Ry(90-phi) and Rz(-lambda) 
       
        double theta=-90.0;
        System.out.println(theta);
        double theta2= 90.0-phi;
        double theta3=-(lambda);
        // Create four matrices
        double Rzminus90[][]={{Math.cos(Math.toRadians(theta)),-(Math.sin(Math.toRadians(theta))),0},{Math.sin(Math.toRadians(theta)),Math.cos(Math.toRadians(theta)),0},{0,0,1}};
        double Ry90minusphi [][]={{Math.cos(Math.toRadians(theta2)),0,-(Math.sin(Math.toRadians(theta2)))},{0,1,0},{Math.sin(Math.toRadians(theta2)),0,Math.cos(Math.toRadians(theta2))}};
        double Rzminuslambda [][]={{Math.cos(Math.toRadians(theta3)),-(Math.sin(Math.toRadians(theta3))),0},{Math.sin(Math.toRadians(theta3)),Math.cos(Math.toRadians(theta3)),0},{0,0,1}};
        double Distancediff [][]= {{dx},{dy},{dz}};
        // Create three matrix variables to store temporary results after matric multiplication
        double temp1[][]= matrixMultiply(Rzminus90,Ry90minusphi);
        double temp2[][]= matrixMultiply(temp1,Rzminuslambda);
        double resultant[][]= matrixMultiply(temp2,Distancediff);
        
        // The resultant matrix will be of 3X1. Hence, the firs element of each row will give us the value of E,N and U
        
        double E= resultant[0][0];
        double N= resultant[1][0];
        double U= resultant[2][0];
        
        // Show the result into the control
        txtEast.setText(String.valueOf(formatter.format(E)));
        txtNorth.setText(String.valueOf(formatter.format(N)));
        txtUp.setText(String.valueOf(formatter.format(U)));
        
        // Calculate Az and El
        
        double Az= 180+Math.toDegrees(Math.atan((E/N)));// Clockwise from true north=> 180 is added(why?)
//        System.out.println(E/N);
//        System.out.println(Math.toDegrees(Math.atan(-1)));
        double El= Math.toDegrees(Math.atan(U/(Math.sqrt(E*E+N*N))));     
        txtAz.setText(String.valueOf(formatter.format(Az)));
        txtEl.setText(String.valueOf(formatter.format(El)));
      
    }//GEN-LAST:event_btnCalculateActionPerformed
    //Function to perform any double array multiplication
        public static double[][] matrixMultiply(double a[][], double b[][]) {

      int aRows = a.length,
          aColumns = a[0].length,
          bRows = b.length,
          bColumns = b[0].length;

      if ( aColumns != bRows ) {
        throw new IllegalArgumentException("A:Rows: " + aColumns + " did not match B:Columns " + bRows + ".");
      }

      double[][] resultant = new double[aRows][bColumns];

      for(int i = 0; i < aRows; i++) { // aRow
        for(int j = 0; j < bColumns; j++) { // bColumn
          for(int k = 0; k < aColumns; k++) { // aColumn
            resultant[i][j] += a[i][k] * b[k][j];
          }
        }  
      }

      return resultant;
    }
    private void btnClearxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearxActionPerformed
        // TODO add your handling code here:
        
        txtSatB.setText("");
        txtSatL.setText("");
        txtSatH.setText("");
        txtSatx.setText("");
        txtSaty.setText("");
        txtSaty.setText("");
        
        txtRx.setText("");
        txtRy.setText("");
        txtRz.setText("");
        txtRB.setText("");
        txtRL.setText("");
        txtRH.setText("");
                       
        txtEast.setText("");
        txtNorth.setText("");
        txtUp.setText("");
        
        txtAz.setText("");
        txtEl.setText("");
    }//GEN-LAST:event_btnClearxActionPerformed

    private void txtSatyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatyActionPerformed

    private void txtSatLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSatLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSatLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GnssConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GnssConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GnssConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GnssConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GnssConversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearx;
    private javax.swing.JButton btnDOY;
    private javax.swing.JButton btnDOYClr;
    private javax.swing.JButton btnECEFtoLLH;
    private javax.swing.JButton btnGPSSec;
    private javax.swing.JButton btnLLH2ECEF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAz;
    private javax.swing.JLabel lblAzEl;
    private javax.swing.JLabel lblDOY;
    private javax.swing.JLabel lblECEF;
    private javax.swing.JLabel lblEast;
    private javax.swing.JLabel lblGPSWeek;
    private javax.swing.JLabel lblGivenPosition;
    private javax.swing.JLabel lblGivenPosition1;
    private javax.swing.JLabel lblGivenPosition2;
    private javax.swing.JLabel lblHeighte;
    private javax.swing.JLabel lblLLH;
    private javax.swing.JLabel lblLatN;
    private javax.swing.JLabel lblLonE;
    private javax.swing.JLabel lblRx;
    private javax.swing.JLabel lblRx1;
    private javax.swing.JLabel lblRy;
    private javax.swing.JLabel lblRy1;
    private javax.swing.JLabel lblRy2;
    private javax.swing.JLabel lblRy3;
    private javax.swing.JLabel lblRz;
    private javax.swing.JLabel lblRz1;
    private javax.swing.JLabel lblSatellite;
    private javax.swing.JLabel lblSatellite1;
    private javax.swing.JLabel lblSatx;
    private javax.swing.JLabel lblSatx1;
    private javax.swing.JLabel lblSaty;
    private javax.swing.JLabel lblSaty1;
    private javax.swing.JLabel lblSatz;
    private javax.swing.JLabel lblSatz1;
    private javax.swing.JLabel lblUp;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JLabel lblZ;
    private javax.swing.JPanel pnlBasic;
    private javax.swing.JPanel pnlECEFllh;
    private javax.swing.JPanel pnlENUAzEl;
    private javax.swing.JPanel pnlToDate;
    private javax.swing.JTextField txtAz;
    private javax.swing.JTextField txtDOY;
    private javax.swing.JTextField txtDateDOY;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtEast;
    private javax.swing.JTextField txtEl;
    private javax.swing.JTextField txtGPSWeek;
    private javax.swing.JTextField txtHeighte;
    private javax.swing.JTextField txtLatN;
    private javax.swing.JTextField txtLonE;
    private javax.swing.JTextField txtNorth;
    private javax.swing.JTextField txtRB;
    private javax.swing.JTextField txtRH;
    private javax.swing.JTextField txtRL;
    private javax.swing.JTextField txtRx;
    private javax.swing.JTextField txtRy;
    private javax.swing.JTextField txtRz;
    private javax.swing.JTextField txtSatB;
    private javax.swing.JTextField txtSatH;
    private javax.swing.JTextField txtSatL;
    private javax.swing.JTextField txtSatx;
    private javax.swing.JTextField txtSaty;
    private javax.swing.JTextField txtSatz;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtUp;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    private javax.swing.JTextField txtZ;
    // End of variables declaration//GEN-END:variables
}
